import React, {useMemo, useState} from 'react';
import Layout from '@theme/Layout';
import {interviewQuestions} from '@site/src/data/interview';
import {progressStore} from '@site/src/components/learning/progressStore';

export default function Interview() {
  const categories = ['All'].concat(Array.from(new Set(interviewQuestions.map((q) => q.category)))); const [category, setCategory] = useState('All'); const [index, setIndex] = useState(0); const [follow, setFollow] = useState(false); const [framework, setFramework] = useState(false); const [answer, setAnswer] = useState(false); const [notes, setNotes] = useState(''); const [level, setLevel] = useState(3);
  const bank = useMemo(() => category === 'All' ? interviewQuestions : interviewQuestions.filter((q) => q.category === category), [category]); const question = bank[index % bank.length];
  const reset = (next = index + 1) => {progressStore.add('interviewAttempted', question.id); setIndex(next % bank.length); setFollow(false); setFramework(false); setAnswer(false); setNotes('');};
  return <Layout title="Interview practice"><main className="pageShell narrow"><header className="pageHeader"><span className="eyebrow">Senior interview mode</span><h1>Reason aloud, then compare</h1><p>Answers stay hidden until requested. The 0–6 scale moves from no familiarity to customer advice and trade-offs.</p></header><div className="filterRow">{categories.map((item) => <button className={category === item ? 'active' : 'secondary'} key={item} onClick={() => {setCategory(item); setIndex(0);}}>{item}</button>)}</div><article className="questionPanel"><span className="eyebrow">{question.category} · question {index + 1}/{bank.length}</span><h2>{question.question}</h2><textarea rows={8} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Structure your answer here before revealing guidance…"/><label>Self-assessed depth: <strong>{level}</strong><input type="range" min="0" max="6" value={level} onChange={(e) => setLevel(Number(e.target.value))}/></label><div className="buttonRow"><button onClick={() => setFollow(!follow)}>Show follow-up</button><button onClick={() => setFramework(!framework)}>Reveal framework</button><button onClick={() => setAnswer(!answer)}>Reveal strong answer</button></div>{follow && <div className="reveal"><strong>Follow-up</strong><p>{question.followUp}</p></div>}{framework && <div className="reveal"><strong>Framework</strong><p>{question.framework}</p></div>}{answer && <div className="reveal answer"><strong>Strong answer</strong><p>{question.answer}</p></div>}<button onClick={() => reset()}>Next question →</button></article></main></Layout>;
}
