import React, {useState} from 'react';
import Layout from '@theme/Layout';
import PythonPlayground, {type PythonExercise} from '@site/src/components/PythonPlayground';

const baseTests = (functionName: string) => `\nprint("Running tests…")\nassert callable(${functionName})\nprint("PASS")`;
const labs: PythonExercise[] = [
  {id:'regex',title:'Regex log parser',prompt:'Parse timestamp, severity, and message from an infrastructure log line.',starter:`import re\n\ndef parse_log(line: str) -> dict:\n    # TODO: return timestamp, severity, message\n    return {}\n\nprint(parse_log("2026-07-30T10:00:00Z ERROR kubelet timeout"))`,expected:`{'timestamp': '2026-07-30T10:00:00Z', 'severity': 'ERROR', ...}`,tests:`assert parse_log("2026-07-30T10:00:00Z ERROR kubelet timeout")["severity"] == "ERROR"\nprint("PASS")`,hint:'Use named capture groups and fullmatch.',solution:`def parse_log(line):\n    m = re.fullmatch(r"(?P<timestamp>\\S+) (?P<severity>DEBUG|INFO|WARN|ERROR) (?P<message>.+)", line)\n    if not m: raise ValueError("invalid log line")\n    return m.groupdict()`,explanation:'Named groups make the parsing contract visible and testable.'},
  {id:'retry',title:'Retries, backoff, and jitter',prompt:'Implement a bounded retry schedule without sleeping.',starter:`import random\n\ndef retry_delays(attempts: int, base: float = 0.5, cap: float = 8.0) -> list[float]:\n    # TODO: exponential backoff with full jitter\n    return []\n\nprint(retry_delays(5))`,expected:'Five delays, each bounded by the exponential cap',tests:`delays = retry_delays(5)\nassert len(delays) == 5\nassert all(0 <= d <= min(8.0, .5 * 2**i) for i, d in enumerate(delays))\nprint("PASS")`,hint:'For attempt i, draw uniformly from zero to min(cap, base * 2**i).',solution:`def retry_delays(attempts, base=0.5, cap=8.0):\n    return [random.uniform(0, min(cap, base * 2**i)) for i in range(attempts)]`,explanation:'Full jitter reduces synchronized retry storms. Real clients must also classify retryable failures and honor total deadlines.'},
  {id:'gpu',title:'GPU inventory parser',prompt:'Normalize nvidia-smi CSV rows into typed inventory records.',starter:`from dataclasses import dataclass\n\n@dataclass(frozen=True)\nclass GPU:\n    uuid: str\n    name: str\n    memory_mb: int\n\ndef parse_inventory(text: str) -> list[GPU]:\n    # TODO\n    return []\n\nsample = "GPU-a, NVIDIA H100, 81559\\nGPU-b, NVIDIA H100, 81559"\nprint(parse_inventory(sample))`,expected:'Two immutable GPU objects',tests:`items = parse_inventory(sample)\nassert len(items) == 2 and items[0].uuid == "GPU-a" and items[1].memory_mb == 81559\nprint("PASS")`,hint:'Split lines, then split each line with a maximum of two commas and strip fields.',solution:`def parse_inventory(text):\n    result = []\n    for line in text.splitlines():\n        uuid, name, memory = (part.strip() for part in line.split(",", 2))\n        result.append(GPU(uuid, name, int(memory)))\n    return result`,explanation:'A typed boundary prevents raw command text from leaking into decision logic.'},
];
const additional = ['Log severity classifier','Large-file streaming parser','Generator pipelines','JSON/YAML validation','pathlib filesystem scanner','Safe subprocess wrapper','Timeout handling','Concurrent host checks','asyncio API collection','Structured logging','Dataclasses and typing','pytest fixtures','Mocks and effects','CLI tooling','Kubernetes diagnostic checker','Production diagnostic CLI'];
for (const [i, title] of additional.entries()) labs.push({id:`lab-${i}`, title, prompt:`Implement the core ${title.toLowerCase()} decision as a pure, testable function.`, starter:`def diagnose(records):\n    """Return a deterministic result without hidden I/O."""\n    # TODO\n    return []\n\nprint(diagnose([]))`, expected:'A deterministic result and passing contract test', tests:`assert diagnose([]) == []\n${baseTests('diagnose')}`, hint:'Keep parsing/decision logic separate from files, processes, network calls, and time.', solution:`def diagnose(records):\n    return [record for record in records if record]`, explanation:'This scaffold emphasizes the production pattern: isolate decisions from effects, then replace it with the volume-specific implementation.'});

export default function Labs() { const [index, setIndex] = useState(0); return <Layout title="Python labs"><main className="pageShell"><header className="pageHeader"><span className="eyebrow">Production Python</span><h1>Browser-side Python playground</h1><p>Python executes only in a disposable browser worker. The first run downloads Pyodide; no visitor code reaches this site’s server.</p></header><div className="labLayout"><aside className="scenarioList">{labs.map((lab, i) => <button className={i === index ? 'active' : ''} onClick={() => setIndex(i)} key={lab.id}>{lab.title}</button>)}</aside><PythonPlayground exercise={labs[index]}/></div></main></Layout>; }
