import React, {useMemo, useState} from 'react';
import Layout from '@theme/Layout';
import {useLocation} from '@docusaurus/router';
import CommandCard, {type Command} from '@site/src/components/learning/CommandCard';

const resources = [
  ['NVIDIA Documentation','Official documentation','CUDA Compatibility','GPU driver and CUDA compatibility','Reference','Validate supported driver/toolkit relationships','https://docs.nvidia.com/deploy/cuda-compatibility/'],
  ['NVIDIA Documentation','Official documentation','GPU Operator','Kubernetes GPU lifecycle','Reference','Understand operands, prerequisites, and troubleshooting boundaries','https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/'],
  ['NVIDIA Documentation','Official documentation','NVIDIA Container Toolkit','Container GPU injection','Reference','Trace runtime configuration and CDI/container integration','https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/'],
  ['NVIDIA Documentation','Official documentation','DCGM','GPU telemetry and health','Reference','Connect health checks, field metrics, diagnostics, and fleet operations','https://docs.nvidia.com/datacenter/dcgm/latest/'],
  ['NVIDIA Developer','Developer guide','NCCL documentation','Collectives and distributed training','Reference','Understand collective behavior, environment controls, and diagnostics','https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/'],
  ['NVIDIA Developer','Developer guide','TensorRT-LLM','Inference optimization','Reference','Study runtime architecture, serving, and performance controls','https://nvidia.github.io/TensorRT-LLM/'],
  ['NVIDIA Documentation','Official documentation','NVIDIA NIM','Model serving','Reference','Understand NIM deployment and supported operational patterns','https://docs.nvidia.com/nim/'],
  ['NVIDIA Developer','Project documentation','Dynamo','Disaggregated inference','Reference','Explore inference orchestration and disaggregated serving concepts','https://docs.nvidia.com/dynamo/'],
  ['Kubernetes','Official documentation','Kubernetes concepts','Kubernetes internals and operations','Reference','Use the canonical API and workload behavior documentation','https://kubernetes.io/docs/concepts/'],
  ['Python','Official documentation','Python 3 documentation','Production Python','Reference','Confirm language, library, typing, asyncio, and subprocess behavior','https://docs.python.org/3/'],
  ['Linux','Kernel documentation','Linux kernel documentation','Host mechanics','Reference','Study cgroups, networking, memory, scheduling, and kernel interfaces','https://docs.kernel.org/'],
  ['CNCF','Project documentation','OpenTelemetry documentation','Metrics, logs, and traces','Reference','Apply semantic conventions and trace context correctly','https://opentelemetry.io/docs/'],
  ['Prometheus','Official documentation','Prometheus documentation','Metrics and PromQL','Reference','Understand the data model, query semantics, and operations','https://prometheus.io/docs/'],
  ['Grafana','Official documentation','Grafana documentation','Dashboards and alerting','Reference','Build operational views and alert workflows','https://grafana.com/docs/grafana/latest/'],
  ['vLLM','Project documentation','vLLM documentation','LLM serving and continuous batching','Reference','Study serving, distributed execution, and operational controls','https://docs.vllm.ai/'],
  ['Udemy','Course landing page','Python for DevOps','Python data structures, files, APIs, testing, and CLI automation','Course','Reinforces the production Python volume; use only your own licensed access','https://www.udemy.com/course/python-devops'],
  ['Udemy','Course landing page','Linux Troubleshooting','Linux services, performance, networking, and incident evidence','Course','Provides additional hands-on host troubleshooting practice','https://www.udemy.com/course/linux-troubleshooting-course'],
  ['Udemy','Course landing page','Kubernetes Troubleshooting','Kubernetes workload and platform incidents','Course','Reinforces evidence-driven Kubernetes incident practice','https://www.udemy.com/course/kubernetes-troubleshooting'],
  ['Coursera','Course landing page','The Bits and Bytes of Computer Networking','Networking foundations','Course','Reinforces routing, TCP/IP, DNS, and network troubleshooting foundations','https://www.coursera.org/learn/computer-networking'],
];
const commands: Command[] = [
  ['ps -eo pid,ppid,stat,psr,comm','Which processes, states, parents, and CPUs exist?','Expected services in runnable/sleeping states','D-state pileup, zombies, restart churn','pidstat -p <pid> 1'],
  ['top -H','Which processes or threads consume CPU/memory now?','Load and consumers match known demand','One hot thread, high load with idle CPU','pidstat -t 1'], ['vmstat 1','Are run queue, memory, paging, I/O wait, and switches pressured?','Stable r, no sustained swap-in/out','r above CPU capacity, si/so or wa spikes','pidstat -dur 1'],
  ['iostat -xz 1','Which block devices are saturated or latent?','Latency and queue near baseline','High await, queue, or utilization with workload stalls','pidstat -d 1'], ['pidstat -dur 1','Which process drives CPU, faults, or I/O?','Demand maps to expected processes','Unexpected faults, waits, or device I/O','strace -p <pid>'],
  ['perf top','Where is CPU time spent?','Hot paths match workload','Kernel/spin/allocator hot paths','perf record -g -p <pid>'], ['strace -p <pid>','Which syscalls block/fail/repeat?','Expected syscall mix','Repeated errors or long blocking calls','strace -ttT -p <pid>'],
  ['ss -s','What is the socket/TCP state summary?','Stable established/time-wait counts','Growing retransmit-related or orphan pressure','ss -tanp'], ['ip route get <peer>','Which route/source/interface reaches the peer?','Expected source and fabric interface','Wrong table, gateway, or interface','ip neigh show'],
  ['ethtool -S <iface>','Do NIC counters show drops/errors/congestion?','Counters stable against baseline','CRC, drop, pause, or queue errors increasing','ethtool <iface>'], ['numactl --hardware','What NUMA nodes and CPU/memory locality exist?','Expected hardware topology','Missing/offline memory or misunderstood locality','nvidia-smi topo -m'],
  ['dmesg -T','What kernel/driver events occurred?','No new hardware/driver faults','OOM, NVRM Xid, link reset, filesystem errors','journalctl -k --since -30m'], ['journalctl -u kubelet','What did the service report across time?','Stable heartbeats and sync loops','GC, runtime, certificate, or CNI errors','systemctl status kubelet'],
  ['kubectl describe pod <pod>','What lifecycle state, conditions, and events exist?','Ready conditions and normal events','Scheduling, mount, pull, probe, or eviction failures','kubectl logs <pod> --previous'], ['crictl ps -a','What does the node runtime know about containers?','Expected running containers','Rapid exits or sandbox failures','crictl inspect <id>'],
  ['nvidia-smi topo -m','How are GPUs, NICs, PCIe, NVLink, and NUMA related?','Expected local links and affinity','Remote paths for communicating ranks','nvidia-smi -q'], ['dcgmi diag -r 2','Does a drained GPU pass controlled diagnostics?','All selected tests pass','Repeatable memory, PCIe, or hardware failure','dmesg -T | grep -i NVRM'],
  ['ibstat','Are InfiniBand ports physically and logically active?','State Active, expected rate/width','Down/Init, wrong rate, unexpected LID','ibv_devinfo'], ['ibv_devinfo','Which RDMA devices, ports, and capabilities exist?','Expected active port and MTU','Wrong link layer, inactive port, MTU mismatch','rdma link show'],
  ['rdma link show','How are RDMA devices mapped and configured?','Expected netdev/port state','Missing or down RDMA link','ib_write_bw <peer>'],
].map(([command, asks, healthy, suspicious, next]) => ({command, asks, healthy, suspicious, next}));

export default function Resources() { const location = useLocation(); const topic = new URLSearchParams(location.search).get('topic') || ''; const [query, setQuery] = useState(topic); const shown = useMemo(() => { const normalized=query.trim().toLowerCase(); if(!normalized)return resources; const terms=normalized.split(/[^a-z0-9.+-]+/).filter(term=>term.length>2&&!['chapter','senior','deep','dive','and','the','for'].includes(term)); const matches=resources.filter(r=>terms.some(term=>r.join(' ').toLowerCase().includes(term))); return matches.length?matches:resources.filter(r=>r[0].startsWith('NVIDIA')).slice(0,8); }, [query]); return <Layout title="Resources and commands"><main className="pageShell"><header className="pageHeader"><span className="eyebrow">Contextual resource layer</span><h1>Official references and command reasoning</h1><p>Use external resources to deepen a source lesson, not to replace it. No paid course content or fabricated deep links are included.</p><input className="searchInput" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Filter by current topic, provider, or technology…"/></header><section><h2>Resources {topic && <small>for “{topic}”</small>}</h2><div className="resourceGrid">{shown.map(([provider,type,title,relevant,duration,why,url]) => <article className="resourceCard" key={url}><span className="eyebrow">{provider} · {type}</span><h3>{title}</h3><dl><dt>Relevant topic</dt><dd>{relevant}</dd><dt>Duration</dt><dd>{duration}</dd><dt>Why useful</dt><dd>{why}</dd></dl><a href={url} target="_blank" rel="noreferrer">Open source ↗</a></article>)}</div></section><section><h2>Troubleshooting command cards</h2><p>Expand a command to see the operational question, evidence patterns, and next step.</p><div className="commandGrid">{commands.map((item) => <CommandCard key={item.command} item={item}/>)}</div></section></main></Layout>; }
