// Generated by scripts/generate-study-context.mjs. Do not edit by hand.
export type ChapterStudyContext = {
  volume: string;
  lens: string;
  learningOutcome: string;
  sections: string[];
  codeLanguages: string[];
};

export const chapterStudyContexts: Record<string, ChapterStudyContext> = {
  "Master Index": {
    "volume": "Academy orientation",
    "lens": "cross-volume senior DevOps and AI-infrastructure practice",
    "learningOutcome": "Curriculum map and guided learning flow for the NVIDIA Senior DevOps and AI Infrastructure Solutions Architect Academy.",
    "sections": [
      "Guided tutor flow",
      "Source architecture"
    ],
    "codeLanguages": []
  },
  "Chapter 1 - Processes, threads, CPU scheduling and load": {
    "volume": "Volume 1",
    "lens": "Linux processes, memory, storage, networking, containers, systemd, and host-level evidence",
    "learningOutcome": "Explain process/thread state, scheduler queues, CPU time, context switches, load average, throttling and the evidence that distinguishes them.",
    "sections": [
      "Chapter 1 — Processes, threads, CPU scheduling and load",
      "1.1 Process and thread model",
      "1.2 Process states",
      "1.3 CPU scheduling, run queue and context switches",
      "vmstat: r=run queue, cs=context switches/s, us/sy/id/wa=CPU state percentages",
      "1.4 CPU quotas and throttling",
      "cgroup v2 examples; exact path depends on runtime",
      "look for nr throttled / throttled usec",
      "Worked scenario",
      "Practice",
      "➕ Going deeper (added — this is the \"even more depth\" pass)",
      "perf and bpftrace for CPU scheduling (beyond vmstat/mpstat)",
      "Scheduling classes, compared (the table the JD's \"advanced\" bar expects)",
      "GPU/AI-adjacent failure scenario (this chapter's concepts, applied to the actual job you're interviewing for)"
    ],
    "codeLanguages": [
      "bash",
      "text"
    ]
  },
  "Chapter 2 - Virtual memory, page cache, swap and OOM": {
    "volume": "Volume 1",
    "lens": "Linux processes, memory, storage, networking, containers, systemd, and host-level evidence",
    "learningOutcome": "Trace allocation from virtual address space through pages, reclaim and cgroup limits; distinguish node OOM from container OOM.",
    "sections": [
      "Chapter 2 — Virtual memory, page cache, swap and OOM",
      "2.1 Virtual memory",
      "2.2 Page cache and \"free memory\"",
      "2.3 OOM at different boundaries",
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "bash",
      "text"
    ]
  },
  "Chapter 3 - Files, file descriptors, filesystems and block I/O": {
    "volume": "Volume 1",
    "lens": "Linux processes, memory, storage, networking, containers, systemd, and host-level evidence",
    "learningOutcome": "Understand how applications reach storage and distinguish capacity, metadata, throughput, IOPS and latency failures.",
    "sections": [
      "Chapter 3 — Files, file descriptors, filesystems and block I/O",
      "3.1 File descriptors and VFS",
      "3.2 Capacity versus latency",
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "bash",
      "text"
    ]
  },
  "Chapter 4 - Networking: IP, routes, sockets, TCP, DNS, NAT and TLS": {
    "volume": "Volume 1",
    "lens": "Linux processes, memory, storage, networking, containers, systemd, and host-level evidence",
    "learningOutcome": "Trace a connection from name lookup through application response and identify what each diagnostic proves.",
    "sections": [
      "Chapter 4 — Networking: IP, routes, sockets, TCP, DNS, NAT and TLS",
      "4.1 Addressing and routing",
      "4.2 Sockets and TCP state",
      "4.3 DNS is a dependency, not magic",
      "search default.svc.cluster.local svc.cluster.local cluster.local example.com",
      "options ndots:5",
      "4.4 NAT, firewall, TLS and HTTP",
      "older systems may use iptables-save",
      "Worked scenario",
      "Practitioner lens",
      "Practice"
    ],
    "codeLanguages": [
      "bash",
      "text"
    ]
  },
  "Chapter 5 - Namespaces, cgroups and container mechanics": {
    "volume": "Volume 1",
    "lens": "Linux processes, memory, storage, networking, containers, systemd, and host-level evidence",
    "learningOutcome": "Explain what a container actually is at the Linux level and how Kubernetes requests/limits map to resource control.",
    "sections": [
      "Chapter 5 — Namespaces, cgroups and container mechanics",
      "5.1 Namespaces",
      "5.2 cgroups",
      "5.3 What an image is — and is not",
      "Worked scenario"
    ],
    "codeLanguages": [
      "bash",
      "text"
    ]
  },
  "Chapter 6 - systemd, boot, services, signals and logs": {
    "volume": "Volume 1",
    "lens": "Linux processes, memory, storage, networking, containers, systemd, and host-level evidence",
    "learningOutcome": "Diagnose why a Linux service failed to start, restarted, stopped accepting traffic or was killed.",
    "sections": [
      "Chapter 6 — systemd, boot, services, signals and logs",
      "6.1 Unit state and dependency model",
      "6.2 Signals and shutdown",
      "Worked scenario"
    ],
    "codeLanguages": [
      "bash",
      "text",
      "python"
    ]
  },
  "Senior Deep Dive 1 — Linux execution: syscalls, scheduling, run queues and CPU pressure": {
    "volume": "Volume 1",
    "lens": "Linux processes, memory, storage, networking, containers, systemd, and host-level evidence",
    "learningOutcome": "Senior Deep Dive 1 — Linux execution: syscalls, scheduling, run queues and CPU pressure — Foundations Beneath Kubernetes.",
    "sections": [
      "Scheduling and context-switch pressure",
      "What is the process actually waiting on?",
      "cgroup v2 CPU control for a container/task",
      "➕ Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 2 — Memory: virtual address space, page faults, NUMA and OOM decisions": {
    "volume": "Volume 1",
    "lens": "Linux processes, memory, storage, networking, containers, systemd, and host-level evidence",
    "learningOutcome": "Senior Deep Dive 2 — Memory: virtual address space, page faults, NUMA and OOM decisions — Foundations Beneath Kubernetes.",
    "sections": [
      "Per-process mappings and faults",
      "NUMA layout and locality",
      "➕ Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 3 — Storage I/O: VFS to NVMe, latency queues and checkpoint behavior": {
    "volume": "Volume 1",
    "lens": "Linux processes, memory, storage, networking, containers, systemd, and host-level evidence",
    "learningOutcome": "Senior Deep Dive 3 — Storage I/O: VFS to NVMe, latency queues and checkpoint behavior — Foundations Beneath Kubernetes.",
    "sections": [
      "Which processes are issuing I/O?",
      "Quick latency test - never run destructive tests on production devices",
      "➕ Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 4 — Packet-level networking: routing, conntrack, TCP and DNS failure modes": {
    "volume": "Volume 1",
    "lens": "Linux processes, memory, storage, networking, containers, systemd, and host-level evidence",
    "learningOutcome": "Senior Deep Dive 4 — Packet-level networking: routing, conntrack, TCP and DNS failure modes — Foundations Beneath Kubernetes.",
    "sections": [
      "Socket and TCP state",
      "Packet evidence",
      "Conntrack / firewall state (tooling varies by distro)",
      "➕ Senior addendum"
    ],
    "codeLanguages": [
      "bash",
      "text"
    ]
  },
  "Senior Deep Dive 5 — Containers: namespaces, cgroups v2, overlay filesystems and runtime boundaries": {
    "volume": "Volume 1",
    "lens": "Linux processes, memory, storage, networking, containers, systemd, and host-level evidence",
    "learningOutcome": "Senior Deep Dive 5 — Containers: namespaces, cgroups v2, overlay filesystems and runtime boundaries — Foundations Beneath Kubernetes.",
    "sections": [
      "Enter a container's network namespace from the host",
      "Inspect cgroup placement and limits",
      "➕ Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 6 — Host readiness for NVIDIA GPU nodes": {
    "volume": "Volume 1",
    "lens": "Linux processes, memory, storage, networking, containers, systemd, and host-level evidence",
    "learningOutcome": "Senior Deep Dive 6 — Host readiness for NVIDIA GPU nodes — Foundations Beneath Kubernetes.",
    "sections": [
      "➕ Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior troubleshooting exercise — Slow GPU job with “healthy” Kubernetes": {
    "volume": "Volume 1",
    "lens": "Linux processes, memory, storage, networking, containers, systemd, and host-level evidence",
    "learningOutcome": "Senior troubleshooting exercise — Slow GPU job with “healthy” Kubernetes — Foundations Beneath Kubernetes.",
    "sections": [
      "➕ Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Book map": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Book map — Python for Production Infrastructure.",
    "sections": [],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 1 - How Python actually executes your infrastructure script": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Chapter 1 - How Python actually executes your infrastructure script — Python for Production Infrastructure.",
    "sections": [
      "{'gpu-1': ['gpu', 'gpu-1', 'gpu-2'], 'gpu-2': ['gpu', 'gpu-1', 'gpu-2']} ← both nodes share one list!",
      "Module execution and \\ \\ name\\ \\",
      "healthcheck.py",
      "Work the scenario step by step",
      "Practice before moving on"
    ],
    "codeLanguages": [
      "python",
      "text",
      "bash"
    ]
  },
  "Chapter 2 - Choosing data structures by the problem, not by habit": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Chapter 2 - Choosing data structures by the problem, not by habit — Python for Production Infrastructure.",
    "sections": [
      "defaultdict — eliminates the \"if key not in dict: dict[key] = []\" boilerplate",
      "{'a': ['gpu-1', 'cpu-1'], 'b': ['gpu-2']}",
      "Counter — frequency counting in one line (e.g. \"which error appears most in this log batch\")",
      "deque — O(1) append/pop from BOTH ends; a list is O(n) to pop from the front",
      "Work the scenario step by step",
      "list-based: ~4.200s set-based: ~0.006s — roughly 700x on this size",
      "Practice before moving on"
    ],
    "codeLanguages": [
      "text",
      "python"
    ]
  },
  "Chapter 3 - Functions: turn scripts into testable decisions": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Chapter 3 - Functions: turn scripts into testable decisions — Python for Production Infrastructure.",
    "sections": [
      "Practice before moving on"
    ],
    "codeLanguages": [
      "python",
      "text"
    ]
  },
  "Chapter 4 - Files, pathlib, regex, JSON and YAML": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Chapter 4 - Files, pathlib, regex, JSON and YAML — Python for Production Infrastructure.",
    "sections": [
      "yaml.load(open(\"config.yaml\")) DANGEROUS without Loader= — can execute arbitrary Python objects",
      "Work the scenario step by step",
      "Practice before moving on"
    ],
    "codeLanguages": [
      "python",
      "text"
    ]
  },
  "Chapter 5 - Exceptions and context managers": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Chapter 5 - Exceptions and context managers — Python for Production Infrastructure.",
    "sections": [
      "finally: fine for one-off cleanup, easy to forget, no reuse",
      "context manager: reusable, composable, can't forget it — prefer this for anything used more than once",
      "Practice before moving on"
    ],
    "codeLanguages": [
      "python",
      "text"
    ]
  },
  "Chapter 6 - Logging for operations, not print-debugging": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Chapter 6 - Logging for operations, not print-debugging — Python for Production Infrastructure.",
    "sections": [
      "at the entry point of a request:",
      "Work the scenario step by step",
      "Practice before moving on"
    ],
    "codeLanguages": [
      "python",
      "text"
    ]
  },
  "Chapter 7 - System interaction and subprocess": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Chapter 7 - System interaction and subprocess — Python for Production Infrastructure.",
    "sections": [
      "Work the scenario step by step",
      "Practice before moving on"
    ],
    "codeLanguages": [
      "python",
      "text"
    ]
  },
  "Chapter 8 - HTTP APIs, timeouts, retries and backoff": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Chapter 8 - HTTP APIs, timeouts, retries and backoff — Python for Production Infrastructure.",
    "sections": [
      "Work the scenario step by step",
      "Practice before moving on"
    ],
    "codeLanguages": [
      "python",
      "text"
    ]
  },
  "Chapter 9 - OOP that helps infrastructure code": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Chapter 9 - OOP that helps infrastructure code — Python for Production Infrastructure.",
    "sections": [
      "Practice before moving on"
    ],
    "codeLanguages": [
      "python",
      "text"
    ]
  },
  "Chapter 10 - Generators and decorators without magic": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Chapter 10 - Generators and decorators without magic — Python for Production Infrastructure.",
    "sections": [
      "Practice before moving on"
    ],
    "codeLanguages": [
      "python",
      "text"
    ]
  },
  "Chapter 11 - Concurrency for infrastructure engineers": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Chapter 11 - Concurrency for infrastructure engineers — Python for Production Infrastructure.",
    "sections": [
      "Work the scenario step by step",
      "Practice before moving on"
    ],
    "codeLanguages": [
      "python",
      "text"
    ]
  },
  "Chapter 12 - Type hints and pytest: make changes safer": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Chapter 12 - Type hints and pytest: make changes safer — Python for Production Infrastructure.",
    "sections": [
      "mytool/client.py",
      "WRONG in the test file:",
      "RIGHT:",
      "Practice before moving on"
    ],
    "codeLanguages": [
      "python",
      "text",
      "bash"
    ]
  },
  "Chapter 13 - Project structure, CLI and CI/CD": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Chapter 13 - Project structure, CLI and CI/CD — Python for Production Infrastructure.",
    "sections": [
      "pyproject.toml",
      ".github/workflows/ci.yml (core idea)",
      "Practice before moving on"
    ],
    "codeLanguages": [
      "text",
      "toml",
      "yaml"
    ]
  },
  "Chapter 14 - Capstone: design a cluster diagnostics CLI": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Chapter 14 - Capstone: design a cluster diagnostics CLI — Python for Production Infrastructure.",
    "sections": [
      "model.py — Ch2/Ch3/Ch12: typed domain values, pure decisions",
      "kubernetes.py — Ch7: subprocess boundary, typed failure",
      "cli.py — Ch6/Ch13: logging, exit codes, entry point",
      "test policy.py — Ch12: pure logic, zero cluster needed",
      "Work the scenario step by step",
      "Field note: practitioner perspective"
    ],
    "codeLanguages": [
      "python",
      "text",
      "bash"
    ]
  },
  "Targeted Udemy study map": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Targeted Udemy study map — Python for Production Infrastructure.",
    "sections": [],
    "codeLanguages": [
      "text"
    ]
  },
  "Final Python checklist": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Final Python checklist — Python for Production Infrastructure.",
    "sections": [],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 1 — The Python object model, mutability and interfaces": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Senior Deep Dive 1 — The Python object model, mutability and interfaces — Python for Production Infrastructure.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "python",
      "text"
    ]
  },
  "Senior Deep Dive 2 — Configuration is an API: validation, secrets and precedence": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Senior Deep Dive 2 — Configuration is an API: validation, secrets and precedence — Python for Production Infrastructure.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 3 — Build API clients that fail safely": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Senior Deep Dive 3 — Build API clients that fail safely — Python for Production Infrastructure.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 4 — Async, threads and processes with backpressure": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Senior Deep Dive 4 — Async, threads and processes with backpressure — Python for Production Infrastructure.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 5 — Subprocess is a process API, not a shell shortcut": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Senior Deep Dive 5 — Subprocess is a process API, not a shell shortcut — Python for Production Infrastructure.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text",
      "python"
    ]
  },
  "Senior Deep Dive 6 — Structured logs, metrics and correlation IDs": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Senior Deep Dive 6 — Structured logs, metrics and correlation IDs — Python for Production Infrastructure.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "json",
      "text"
    ]
  },
  "Senior Deep Dive 7 — Testing infrastructure code: isolate decisions from effects": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Senior Deep Dive 7 — Testing infrastructure code: isolate decisions from effects — Python for Production Infrastructure.",
    "sections": [
      "test\\ retry.py",
      "Senior addendum"
    ],
    "codeLanguages": [
      "python",
      "text"
    ]
  },
  "Senior Deep Dive 8 — Complete project: GPU fleet health CLI": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Senior Deep Dive 8 — Complete project: GPU fleet health CLI — Python for Production Infrastructure.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "python",
      "text"
    ]
  },
  "Performance and profiling for operational Python": {
    "volume": "Volume 2",
    "lens": "production Python design, testing, APIs, concurrency, subprocess safety, observability, and automation",
    "learningOutcome": "Performance and profiling for operational Python — Python for Production Infrastructure.",
    "sections": [
      "external sampler if available:",
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 1 - API server, etcd and the object model": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Trace reads/writes, resourceVersion, watches and declarative desired state through the API control plane.",
    "sections": [
      "Chapter 1 — API server, etcd and the object model",
      "1.1 API objects are records of desired/observed state",
      "edit /tmp/a.yaml, apply it — succeeds, resourceVersion bumps",
      "now try to apply the stale /tmp/b.yaml which still carries the OLD resourceVersion",
      "1.2 Watches and reconciliation",
      "Worked scenario",
      "Practice",
      "➕ Going deeper",
      "etcd storage encoding and what actually gets written",
      "API discovery — the other thing the API server serves"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 2 - Scheduler mechanics, resources and topology": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Explain filter/score thinking, requests/allocatable, affinity, taints, topology and extended GPU resources.",
    "sections": [
      "Chapter 2 — Scheduler mechanics, resources and topology",
      "2.1 Requests drive placement",
      "2.2 Constraints: taints, affinity and topology",
      "2.3 Extended resources and GPUs",
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 3 - Kubelet, CRI and Pod lifecycle": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Understand how an assigned Pod becomes namespaces, cgroups, volumes, network setup and running containers on a node.",
    "sections": [
      "Chapter 3 — Kubelet, CRI and Pod lifecycle",
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 4 - Kubernetes networking from Service to CNI": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Trace DNS, Service selection, data plane implementation, CNI routing and NetworkPolicy.",
    "sections": [
      "Chapter 4 — Kubernetes networking from Service to CNI",
      "4.1 Service and EndpointSlice",
      "4.2 Data plane implementation",
      "4.3 DNS, CNI and policy",
      "Practitioner lens",
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 5 - Storage and StatefulSets": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Understand CSI provisioning/attach/mount, PVC binding modes, topology and StatefulSet identity.",
    "sections": [
      "Chapter 5 — Storage and StatefulSets",
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 6 - Security: authentication, RBAC, workload identity and Pod hardening": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Reason about who can call the API, what they can do, how workloads obtain cloud identity and how container privileges change risk.",
    "sections": [
      "Chapter 6 — Security: authentication, RBAC, workload identity and Pod hardening",
      "6.1 RBAC is authorization over API verbs/resources",
      "then check cloud side (example AWS IRSA / EKS pod identity):",
      "6.2 Pod security context",
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 7 - Autoscaling and capacity": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Understand HPA/VPA/KEDA signals, cluster autoscaler constraints and why application scaling and node scaling are different loops.",
    "sections": [
      "Chapter 7 — Autoscaling and capacity",
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 8 - Operators, GitOps and platform engineering": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Use reconciliation to package domain operations and expose safe self-service without hiding operational truth.",
    "sections": [
      "Chapter 8 — Operators, GitOps and platform engineering",
      "Useful Flux-style evidence",
      "Practitioner lens",
      "Practice"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 9 - Upgrades, reliability and cluster operations": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Plan control-plane/node changes around skew, disruption budgets, workload topology and rollback evidence.",
    "sections": [
      "Chapter 9 — Upgrades, reliability and cluster operations",
      "Practice",
      "➕ Going deeper",
      "Rollback evidence — what to actually capture before you need it",
      "Mnemonic for this whole chapter"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Senior Deep Dive 1 — API machinery: resourceVersion, watches, finalizers and ownership": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Senior Deep Dive 1 — API machinery: resourceVersion, watches, finalizers and ownership — Kubernetes and Platform Engineering.",
    "sections": [
      "Senior addendum",
      "Original section preamble (preserved verbatim)",
      "Quick cross-reference (use both halves together, not as duplicates)",
      "Deep Dive 1 — API machinery"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 2 — etcd quorum, control-plane failure and recovery boundaries": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Senior Deep Dive 2 — etcd quorum, control-plane failure and recovery boundaries — Kubernetes and Platform Engineering.",
    "sections": [
      "Senior addendum",
      "Deep Dive 2 — etcd quorum and control-plane failure boundaries"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 3 — Scheduling framework, preemption, gang/topology and DRA": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Senior Deep Dive 3 — Scheduling framework, preemption, gang/topology and DRA — Kubernetes and Platform Engineering.",
    "sections": [
      "DRA resources on clusters that support them",
      "Senior addendum",
      "Deep Dive 3 — Scheduling framework, preemption, gang/topology and DRA"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Senior Deep Dive 4 — Kubelet, CRI, pod sandbox and node pressure": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Senior Deep Dive 4 — Kubelet, CRI, pod sandbox and node pressure — Kubernetes and Platform Engineering.",
    "sections": [
      "Senior addendum",
      "Deep Dive 4 — Kubelet, CRI, pod sandbox and node pressure"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 5 — Networking: Service abstraction, CNI dataplane, DNS and Gateway API": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Senior Deep Dive 5 — Networking: Service abstraction, CNI dataplane, DNS and Gateway API — Kubernetes and Platform Engineering.",
    "sections": [
      "DNS from inside the workload namespace",
      "Node dataplane - varies by CNI/proxy implementation",
      "Senior addendum",
      "Deep Dive 5 — Networking: Service, CNI dataplane, DNS, Gateway API"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 6 — Admission, policy and multi-tenant guardrails": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Senior Deep Dive 6 — Admission, policy and multi-tenant guardrails — Kubernetes and Platform Engineering.",
    "sections": [
      "Namespace Pod Security Admission example",
      "Inspect admission webhooks and policies",
      "Senior addendum",
      "Deep Dive 6 — Admission, policy and multi-tenant guardrails"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Senior Deep Dive 7 — Platform patterns from the Staff Engineer guide": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Senior Deep Dive 7 — Platform patterns from the Staff Engineer guide — Kubernetes and Platform Engineering.",
    "sections": [
      "Senior addendum",
      "Deep Dive 7 — Platform patterns from the Staff Engineer guide"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 8 — GPU platform operations: node pools, operators and resource isolation": {
    "volume": "Volume 3",
    "lens": "Kubernetes control-plane mechanics, scheduling, kubelet/CRI, networking, storage, security, autoscaling, operators, and upgrades",
    "learningOutcome": "Senior Deep Dive 8 — GPU platform operations: node pools, operators and resource isolation — Kubernetes and Platform Engineering.",
    "sections": [
      "Senior addendum",
      "Deep Dive 8 — GPU platform operations",
      "Self-check: original subtopics accounted for"
    ],
    "codeLanguages": [
      "bash",
      "text"
    ]
  },
  "Chapter 1 - GPU execution and memory mental model": {
    "volume": "Volume 4",
    "lens": "GPU execution, memory and topology, drivers/CUDA, device plugins, GPU Operator, sharing, telemetry, and fleet health",
    "learningOutcome": "Explain why GPUs favor throughput parallelism and how compute, HBM bandwidth and data movement become separate bottlenecks.",
    "sections": [
      "1.1 Utilization is not a complete performance model",
      "gpu pwr gtemp mtemp sm mem enc dec jpg ofa mclk pclk",
      "Idx W C C % % % % % % MHz MHz"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 2 - PCIe, NVLink and topology": {
    "volume": "Volume 4",
    "lens": "GPU execution, memory and topology, drivers/CUDA, device plugins, GPU Operator, sharing, telemetry, and fleet health",
    "learningOutcome": "Understand why \"same number of GPUs\" can produce different performance depending on physical connectivity and NUMA placement.",
    "sections": [
      "Worked scenario"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 3 - Driver, CUDA runtime and container stack": {
    "volume": "Volume 4",
    "lens": "GPU execution, memory and topology, drivers/CUDA, device plugins, GPU Operator, sharing, telemetry, and fleet health",
    "learningOutcome": "Know which layer must be compatible and which parts are host versus container responsibility.",
    "sections": [],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 4 - Kubernetes device plugins and GPU Operator": {
    "volume": "Volume 4",
    "lens": "GPU execution, memory and topology, drivers/CUDA, device plugins, GPU Operator, sharing, telemetry, and fleet health",
    "learningOutcome": "Trace how hardware becomes an allocatable Kubernetes extended resource and how operator lifecycle automation fits around it.",
    "sections": [
      "Worked scenario"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 5 - GPU sharing: MIG, time slicing, MPS and vGPU": {
    "volume": "Volume 4",
    "lens": "GPU execution, memory and topology, drivers/CUDA, device plugins, GPU Operator, sharing, telemetry, and fleet health",
    "learningOutcome": "Choose sharing based on isolation, latency determinism, memory behavior, hardware support and operational model.",
    "sections": [
      "Practitioner lens"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 6 - GPU telemetry, DCGM and health": {
    "volume": "Volume 4",
    "lens": "GPU execution, memory and topology, drivers/CUDA, device plugins, GPU Operator, sharing, telemetry, and fleet health",
    "learningOutcome": "Interpret hardware telemetry in the context of workload performance and distinguish demand, health and throttling.",
    "sections": [
      "Prometheus-style examples vary by exporter version/config",
      "clocks.sm well below clocks.max.sm + a non-empty clocks event reasons.active = throttled right now, not idle-by-choice"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 7 - Capacity and failure-domain design": {
    "volume": "Volume 4",
    "lens": "GPU execution, memory and topology, drivers/CUDA, device plugins, GPU Operator, sharing, telemetry, and fleet health",
    "learningOutcome": "Plan GPU pools around workload shape, topology, maintenance, spare capacity and heterogeneous generations.",
    "sections": [
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 1 — GPU execution model without CUDA-programming overload": {
    "volume": "Volume 4",
    "lens": "GPU execution, memory and topology, drivers/CUDA, device plugins, GPU Operator, sharing, telemetry, and fleet health",
    "learningOutcome": "Senior Deep Dive 1 — GPU execution model without CUDA-programming overload — GPU and Accelerated Computing Foundations.",
    "sections": [
      "Senior addendum",
      "Original Fourth Edition Senior Engineering Expansion framing",
      "Quick cross-reference (so you use both halves together, not as duplicates)",
      "Deep Dive 1 — GPU execution model without CUDA-programming overload"
    ],
    "codeLanguages": []
  },
  "Senior Deep Dive 2 — Topology: PCIe, NVLink, NVSwitch and NUMA": {
    "volume": "Volume 4",
    "lens": "GPU execution, memory and topology, drivers/CUDA, device plugins, GPU Operator, sharing, telemetry, and fleet health",
    "learningOutcome": "Senior Deep Dive 2 — Topology: PCIe, NVLink, NVSwitch and NUMA — GPU and Accelerated Computing Foundations.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 3 — Driver, CUDA compatibility and container integration": {
    "volume": "Volume 4",
    "lens": "GPU execution, memory and topology, drivers/CUDA, device plugins, GPU Operator, sharing, telemetry, and fleet health",
    "learningOutcome": "Senior Deep Dive 3 — Driver, CUDA compatibility and container integration — GPU and Accelerated Computing Foundations.",
    "sections": [
      "Runtime integration (commands depend on installation)",
      "Container smoke test",
      "or run a vendor-supported CUDA container through your normal runtime",
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 4 — GPU Operator as a dependency reconciler": {
    "volume": "Volume 4",
    "lens": "GPU execution, memory and topology, drivers/CUDA, device plugins, GPU Operator, sharing, telemetry, and fleet health",
    "learningOutcome": "Senior Deep Dive 4 — GPU Operator as a dependency reconciler — GPU and Accelerated Computing Foundations.",
    "sections": [
      "Senior addendum",
      "Ready ← the whole operand set has converged; if any operand DaemonSet isn't"
    ],
    "codeLanguages": [
      "bash",
      "text"
    ]
  },
  "Senior Deep Dive 5 — Sharing: MIG, time-slicing, MPS and vGPU": {
    "volume": "Volume 4",
    "lens": "GPU execution, memory and topology, drivers/CUDA, device plugins, GPU Operator, sharing, telemetry, and fleet health",
    "learningOutcome": "Senior Deep Dive 5 — Sharing: MIG, time-slicing, MPS and vGPU — GPU and Accelerated Computing Foundations.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": []
  },
  "Senior Deep Dive 6 — DCGM, Xid, ECC and health semantics": {
    "volume": "Volume 4",
    "lens": "GPU execution, memory and topology, drivers/CUDA, device plugins, GPU Operator, sharing, telemetry, and fleet health",
    "learningOutcome": "Senior Deep Dive 6 — DCGM, Xid, ECC and health semantics — GPU and Accelerated Computing Foundations.",
    "sections": [
      "DCGM tooling if deployed",
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 7 — Fleet lifecycle: upgrades, draining and known-good validation": {
    "volume": "Volume 4",
    "lens": "GPU execution, memory and topology, drivers/CUDA, device plugins, GPU Operator, sharing, telemetry, and fleet health",
    "learningOutcome": "Senior Deep Dive 7 — Fleet lifecycle: upgrades, draining and known-good validation — GPU and Accelerated Computing Foundations.",
    "sections": [
      "Senior addendum",
      "1. Driver/CUDA boundary proof (Ch3/Deep Dive 3)",
      "2. Topology unchanged after firmware/driver update (Ch2/Deep Dive 2)",
      "3. Hardware health (Ch6/Deep Dive 6)",
      "4. A representative real workload smoke test — a short training step or inference request,",
      "not just device enumeration — because Xid 31-class bugs can be application/kernel-path",
      "specific and won't show up in nvidia-smi or dcgmi diag alone"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 1 - Classify the AI workload before designing infrastructure": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Distinguish training, fine-tuning, evaluation, batch inference and online inference by compute, communication, storage and SLO behavior.",
    "sections": [],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 2 - Training architecture: compute, data, checkpoints and collectives": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Understand why distributed training depends on GPU topology, fabric, storage and scheduler behavior.",
    "sections": [
      "2.1 Parallelism vocabulary for infrastructure",
      "Worked scenario",
      "gpu pwr gtemp mtemp sm mem enc dec mclk pclk",
      "Idx W C C % % % % MHz MHz"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 3 - LLM inference: prefill, decode, batching and KV cache": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Connect model-serving mechanics to memory, latency, throughput and scaling decisions.",
    "sections": [
      "Practitioner lens"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 4 - Serving frameworks and the platform boundary": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Place Triton, NIM, vLLM and application gateways in an architecture without treating product names as the design.",
    "sections": [
      "Example Kubernetes resource boundary (illustrative)"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 5 - Autoscaling inference": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Choose signals that represent demand and saturation, then account for model-load time, GPU granularity and cold capacity.",
    "sections": [
      "Practitioner lens",
      "Worked scenario"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 6 - Distributed and disaggregated inference": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Understand when multi-GPU/multi-node inference is necessary and what new failure/performance dependencies appear.",
    "sections": [],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 7 - State, caches and RAG dependencies": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Classify durable state, request state, model artifacts, vector data and caches so replicas can scale safely.",
    "sections": [
      "Practitioner lens"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 8 - Security and tenancy for AI platforms": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Apply familiar platform security controls to models, prompts, data, artifacts and shared GPUs.",
    "sections": [],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 9 - Performance and cost engineering": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Translate benchmarks into capacity, cost per unit work and headroom under real request distributions.",
    "sections": [
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 1 — Training systems: parallelism, collectives and checkpoint economics": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Senior Deep Dive 1 — Training systems: parallelism, collectives and checkpoint economics — AI Workloads and AI Platform Architecture.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 2 — LLM inference: prefill, decode, KV cache and continuous batching": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Senior Deep Dive 2 — LLM inference: prefill, decode, KV cache and continuous batching — AI Workloads and AI Platform Architecture.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 3 — NIM, vLLM, TensorRT-LLM and serving boundaries": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Senior Deep Dive 3 — NIM, vLLM, TensorRT-LLM and serving boundaries — AI Workloads and AI Platform Architecture.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 4 — NVIDIA Dynamo: system-level inference optimization": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Senior Deep Dive 4 — NVIDIA Dynamo: system-level inference optimization — AI Workloads and AI Platform Architecture.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 5 — Autoscaling inference from work, not only CPU": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Senior Deep Dive 5 — Autoscaling inference from work, not only CPU — AI Workloads and AI Platform Architecture.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 6 — RAG, vector search and stateful dependencies": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Senior Deep Dive 6 — RAG, vector search and stateful dependencies — AI Workloads and AI Platform Architecture.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 7 — Agentic and multimodal infrastructure": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Senior Deep Dive 7 — Agentic and multimodal infrastructure — AI Workloads and AI Platform Architecture.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 8 — Production benchmark design": {
    "volume": "Volume 5",
    "lens": "training and inference workload mechanics, model serving, KV cache, autoscaling, RAG, security, performance, and benchmarking",
    "learningOutcome": "Senior Deep Dive 8 — Production benchmark design — AI Workloads and AI Platform Architecture.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 1 - Distributed systems performance for GPU jobs": {
    "volume": "Volume 6",
    "lens": "distributed systems, Ethernet/InfiniBand/RoCE, RDMA, NCCL, GPUDirect, storage pipelines, Slurm, and topology-aware scheduling",
    "learningOutcome": "Build a scaling-efficiency model that separates compute, communication, synchronization and I/O.",
    "sections": [
      "Example: 8 GPUs give 6.4x throughput - 80% scaling efficiency",
      "size count type redop time algbw busbw wrong",
      "Out-of-place hack: time in us, algbw/busbw in GB/s",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 2 - Ethernet fundamentals for AI fabrics": {
    "volume": "Volume 6",
    "lens": "distributed systems, Ethernet/InfiniBand/RoCE, RDMA, NCCL, GPUDirect, storage pipelines, Slurm, and topology-aware scheduling",
    "learningOutcome": "Understand link speed, MTU, queues, loss, ECMP and congestion before learning RoCE.",
    "sections": [
      "Practice"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 3 - RDMA, RoCE and InfiniBand": {
    "volume": "Volume 6",
    "lens": "distributed systems, Ethernet/InfiniBand/RoCE, RDMA, NCCL, GPUDirect, storage pipelines, Slurm, and topology-aware scheduling",
    "learningOutcome": "Explain remote memory operations, queue pairs and why loss/congestion configuration matters.",
    "sections": [
      "Perftest tools such as ib write bw / ib read bw may be used in controlled labs.",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 4 - GPUDirect RDMA, NIC/GPU topology and NCCL": {
    "volume": "Volume 6",
    "lens": "distributed systems, Ethernet/InfiniBand/RoCE, RDMA, NCCL, GPUDirect, storage pipelines, Slurm, and topology-aware scheduling",
    "learningOutcome": "Connect GPU collectives to host topology and fabric evidence.",
    "sections": [
      "NCCL debug is powerful but verbose; enable deliberately in a test/incident window.",
      "48 via NET/IB/0/GDRDMA ← healthy — most cross-node channels using GPUDirect RDMA",
      "2 via NET/IB/0/IB ← these 2 fell back to staged path — investigate these specific channels/nodes",
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 5 - NVIDIA Network Operator and Kubernetes accelerated networking": {
    "volume": "Volume 6",
    "lens": "distributed systems, Ethernet/InfiniBand/RoCE, RDMA, NCCL, GPUDirect, storage pipelines, Slurm, and topology-aware scheduling",
    "learningOutcome": "Understand the software automation layer that prepares nodes for high-performance network devices and secondary networks.",
    "sections": [
      "empty output = both operator stacks are fully reconciled on this node; anything listed is your starting point",
      "Practice"
    ],
    "codeLanguages": [
      "text",
      "bash"
    ]
  },
  "Chapter 6 - Storage for AI: datasets, checkpoints and model distribution": {
    "volume": "Volume 6",
    "lens": "distributed systems, Ethernet/InfiniBand/RoCE, RDMA, NCCL, GPUDirect, storage pipelines, Slurm, and topology-aware scheduling",
    "learningOutcome": "Design storage by access pattern, concurrency, locality and recovery behavior.",
    "sections": [
      "Worked scenario",
      "gpu sm mem enc dec"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 7 - Slurm scheduling model": {
    "volume": "Volume 6",
    "lens": "distributed systems, Ethernet/InfiniBand/RoCE, RDMA, NCCL, GPUDirect, storage pipelines, Slurm, and topology-aware scheduling",
    "learningOutcome": "Understand jobs, allocations, partitions, nodes and why HPC schedulers optimize a different operating model from general service orchestration.",
    "sections": [
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 8 - Kubernetes, Slurm or both": {
    "volume": "Volume 6",
    "lens": "distributed systems, Ethernet/InfiniBand/RoCE, RDMA, NCCL, GPUDirect, storage pipelines, Slurm, and topology-aware scheduling",
    "learningOutcome": "Choose orchestration by workload and operating model, not by platform loyalty.",
    "sections": [
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 1 — Collective communication and straggler amplification": {
    "volume": "Volume 6",
    "lens": "distributed systems, Ethernet/InfiniBand/RoCE, RDMA, NCCL, GPUDirect, storage pipelines, Slurm, and topology-aware scheduling",
    "learningOutcome": "Senior Deep Dive 1 — Collective communication and straggler amplification — HPC, Networking and Storage for AI.",
    "sections": [
      "NCCL diagnostics - enable only for diagnosis because logs can be large",
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 2 — RDMA: InfiniBand versus RoCE": {
    "volume": "Volume 6",
    "lens": "distributed systems, Ethernet/InfiniBand/RoCE, RDMA, NCCL, GPUDirect, storage pipelines, Slurm, and topology-aware scheduling",
    "learningOutcome": "Senior Deep Dive 2 — RDMA: InfiniBand versus RoCE — HPC, Networking and Storage for AI.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 3 — Network design for AI: oversubscription, rails and failure domains": {
    "volume": "Volume 6",
    "lens": "distributed systems, Ethernet/InfiniBand/RoCE, RDMA, NCCL, GPUDirect, storage pipelines, Slurm, and topology-aware scheduling",
    "learningOutcome": "Senior Deep Dive 3 — Network design for AI: oversubscription, rails and failure domains — HPC, Networking and Storage for AI.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 4 — Storage hierarchy and data pipeline architecture": {
    "volume": "Volume 6",
    "lens": "distributed systems, Ethernet/InfiniBand/RoCE, RDMA, NCCL, GPUDirect, storage pipelines, Slurm, and topology-aware scheduling",
    "learningOutcome": "Senior Deep Dive 4 — Storage hierarchy and data pipeline architecture — HPC, Networking and Storage for AI.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 5 — Slurm concepts beyond sbatch": {
    "volume": "Volume 6",
    "lens": "distributed systems, Ethernet/InfiniBand/RoCE, RDMA, NCCL, GPUDirect, storage pipelines, Slurm, and topology-aware scheduling",
    "learningOutcome": "Senior Deep Dive 5 — Slurm concepts beyond sbatch — HPC, Networking and Storage for AI.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 6 — Kubernetes, Slurm and hybrid scheduling": {
    "volume": "Volume 6",
    "lens": "distributed systems, Ethernet/InfiniBand/RoCE, RDMA, NCCL, GPUDirect, storage pipelines, Slurm, and topology-aware scheduling",
    "learningOutcome": "Senior Deep Dive 6 — Kubernetes, Slurm and hybrid scheduling — HPC, Networking and Storage for AI.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 7 — Distributed-system patterns from the Staff Engineer guide": {
    "volume": "Volume 6",
    "lens": "distributed systems, Ethernet/InfiniBand/RoCE, RDMA, NCCL, GPUDirect, storage pipelines, Slurm, and topology-aware scheduling",
    "learningOutcome": "Senior Deep Dive 7 — Distributed-system patterns from the Staff Engineer guide — HPC, Networking and Storage for AI.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 1 - Metrics, logs and traces as different evidence": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Know what each telemetry type preserves and choose it by question.",
    "sections": [
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 2 - SLIs, SLOs and error budgets": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Connect reliability work to measurable user outcomes instead of infrastructure percentages.",
    "sections": [
      "99.9% availability - 0.1% error budget over the window",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 3 - Prometheus mental model and PromQL reasoning": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Understand counters, gauges, histograms, rates and label dimensions before copying queries.",
    "sections": [
      "Request rate",
      "5xx ratio",
      "or, more directly, ask \"does any label on this metric have unbounded distinct values?\"",
      "unbounded label smell test: user id, request id, session id, pod UID, raw prompt text, IP address",
      "Practice"
    ],
    "codeLanguages": [
      "promql",
      "text",
      "bash"
    ]
  },
  "Chapter 4 - Kubernetes observability: object state plus runtime evidence": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Combine kube-state-style desired/observed state, kubelet/container metrics and application telemetry.",
    "sections": [
      "Practice"
    ],
    "codeLanguages": [
      "bash",
      "text"
    ]
  },
  "Chapter 5 - GPU observability with DCGM": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Separate device health/utilization from workload demand and performance.",
    "sections": [
      "Practitioner lens",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 6 - Logs that survive incidents": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Design event fields, severity and correlation; prevent secrets and noisy duplication.",
    "sections": [
      "{\"event\": \"inference request\", \"model\": \"llama-x\", \"prompt\": \"<redacted \", \"duration ms\": 812}",
      "Practice"
    ],
    "codeLanguages": [
      "json",
      "text",
      "python"
    ]
  },
  "Chapter 7 - Traces and distributed latency": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Use spans to decompose request latency across gateway, queue, model server and dependencies.",
    "sections": [
      "Practice"
    ],
    "codeLanguages": [
      "text",
      "json"
    ]
  },
  "Chapter 8 - Alert design and runbooks": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Alert on actionable risk to an SLO or critical dependency, then make the first diagnostic steps deterministic.",
    "sections": [
      "Practice"
    ],
    "codeLanguages": [
      "text",
      "json"
    ]
  },
  "Chapter 9 - Incident playbook: Pending Pods, CrashLoops and OOM": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Use object/event evidence before host-level investigation, then descend the stack.",
    "sections": [
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "text",
      "yaml"
    ]
  },
  "Chapter 10 - Incident playbook: GPU workload slow or failing": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Walk from workload SLO through GPU, container/runtime, host, network and storage evidence.",
    "sections": [
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 11 - Incident communication and postmortem": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Separate mitigation, root cause, contributing factors and prevention; communicate by audience.",
    "sections": [
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 1 — Start with SLO impact and scope": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Senior Deep Dive 1 — Start with SLO impact and scope — Observability, Reliability and Troubleshooting.",
    "sections": [
      "Senior addendum",
      "Quick cross-reference (use both halves together, not as duplicates)",
      "Senior Deep Dive 1 — Start with SLO impact and scope"
    ],
    "codeLanguages": []
  },
  "Senior Deep Dive 2 — Prometheus internals, cardinality and query cost": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Senior Deep Dive 2 — Prometheus internals, cardinality and query cost — Observability, Reliability and Troubleshooting.",
    "sections": [
      "p95 from histogram buckets",
      "GPU utilization grouped by node (metric names depend on exporter/version)",
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 3 — OpenTelemetry and trace context across AI services": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Senior Deep Dive 3 — OpenTelemetry and trace context across AI services — Observability, Reliability and Troubleshooting.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 4 — GPU observability with DCGM and driver evidence": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Senior Deep Dive 4 — GPU observability with DCGM and driver evidence — Observability, Reliability and Troubleshooting.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 5 — Inference observability: TTFT, ITL/TPOT and saturation": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Senior Deep Dive 5 — Inference observability: TTFT, ITL/TPOT and saturation — Observability, Reliability and Troubleshooting.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 6 — Incident workflow: evidence tree and safe mitigation": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Senior Deep Dive 6 — Incident workflow: evidence tree and safe mitigation — Observability, Reliability and Troubleshooting.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 7 — Alert design for expensive GPU systems": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Senior Deep Dive 7 — Alert design for expensive GPU systems — Observability, Reliability and Troubleshooting.",
    "sections": [
      "Senior addendum",
      "BAD (single-signal, exactly what this Deep Dive warns against):",
      "BETTER (multi-signal — sustained SLO violation AND queue saturation together):"
    ],
    "codeLanguages": [
      "promql",
      "text"
    ]
  },
  "Senior Deep Dive 8 — Reliability testing and game days": {
    "volume": "Volume 7",
    "lens": "metrics/logs/traces, SLOs, Prometheus, GPU and inference observability, incident response, alerting, and reliability testing",
    "learningOutcome": "Senior Deep Dive 8 — Reliability testing and game days — Observability, Reliability and Troubleshooting.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 1 - Discovery that changes the architecture": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Turn \"we need an AI platform\" into workload, SLO, scale, security, operations and cost facts.",
    "sections": [
      "Practitioner lens",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 2 - Architecture from data and control paths": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Chapter 2 - Architecture from data and control paths — Senior Solutions Architecture Practice.",
    "sections": [
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 3 - Trade-off matrices with weighted requirements": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Chapter 3 - Trade-off matrices with weighted requirements — Senior Solutions Architecture Practice.",
    "sections": [
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 4 - Kubernetes versus Slurm decision workshop": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Chapter 4 - Kubernetes versus Slurm decision workshop — Senior Solutions Architecture Practice.",
    "sections": [
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 5 - GPU sharing and capacity recommendation": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Chapter 5 - GPU sharing and capacity recommendation — Senior Solutions Architecture Practice.",
    "sections": [
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 6 - PoC design: test uncertainty, not product demos": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Chapter 6 - PoC design: test uncertainty, not product demos — Senior Solutions Architecture Practice.",
    "sections": [
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 7 - TCO and capacity conversations": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Chapter 7 - TCO and capacity conversations — Senior Solutions Architecture Practice.",
    "sections": [
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 8 - Security architecture and governance": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Chapter 8 - Security architecture and governance — Senior Solutions Architecture Practice.",
    "sections": [
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 9 - Migration and adoption strategy": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Chapter 9 - Migration and adoption strategy — Senior Solutions Architecture Practice.",
    "sections": [
      "Worked scenario",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 10 - Customer communication and executive explanation": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Chapter 10 - Customer communication and executive explanation — Senior Solutions Architecture Practice.",
    "sections": [
      "Practitioner lens",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 1 — Workload characterization before architecture": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Senior Deep Dive 1 — Workload characterization before architecture — Senior Solutions Architecture Practice.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 2 — AI factory layered architecture": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Senior Deep Dive 2 — AI factory layered architecture — Senior Solutions Architecture Practice.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 3 — Capacity and TCO: convert SLO into resources": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Senior Deep Dive 3 — Capacity and TCO: convert SLO into resources — Senior Solutions Architecture Practice.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 4 — PoC design: test the uncertainty": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Senior Deep Dive 4 — PoC design: test the uncertainty — Senior Solutions Architecture Practice.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 5 — Security and governance for GPU/AI platforms": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Senior Deep Dive 5 — Security and governance for GPU/AI platforms — Senior Solutions Architecture Practice.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 6 — Decision workshops: Kubernetes, Slurm, Run:ai, NIM and Dynamo": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Senior Deep Dive 6 — Decision workshops: Kubernetes, Slurm, Run:ai, NIM and Dynamo — Senior Solutions Architecture Practice.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 7 — Communicate at three levels": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Senior Deep Dive 7 — Communicate at three levels — Senior Solutions Architecture Practice.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Deep Dive 8 — Practitioner role model: Solutions Architect versus implementation engineer": {
    "volume": "Volume 8",
    "lens": "customer discovery, architecture trade-offs, Kubernetes versus Slurm, capacity/TCO, PoCs, security, migration, and executive communication",
    "learningOutcome": "Senior Deep Dive 8 — Practitioner role model: Solutions Architect versus implementation engineer — Senior Solutions Architecture Practice.",
    "sections": [
      "Senior addendum"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 1 - The answer framework: expose your reasoning": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Chapter 1 - The answer framework: expose your reasoning — JR2018680 Interview Preparation.",
    "sections": [
      "Senior Engineering Expansion preface (Fourth Edition, Volume 9)",
      "➕ Additions",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 2 - Python coding interview workflow": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Chapter 2 - Python coding interview workflow — JR2018680 Interview Preparation.",
    "sections": [
      "➕ Additions",
      "Practice"
    ],
    "codeLanguages": [
      "text",
      "python"
    ]
  },
  "Chapter 3 - Linux troubleshooting questions": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Chapter 3 - Linux troubleshooting questions — JR2018680 Interview Preparation.",
    "sections": [
      "Worked scenario",
      "➕ Additions",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 4 - Kubernetes troubleshooting questions": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Chapter 4 - Kubernetes troubleshooting questions — JR2018680 Interview Preparation.",
    "sections": [
      "Worked scenario",
      "➕ Additions",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 5 - GPU and AI infrastructure troubleshooting": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Chapter 5 - GPU and AI infrastructure troubleshooting — JR2018680 Interview Preparation.",
    "sections": [
      "Worked scenario",
      "➕ Additions"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 6 - AI inference architecture questions": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Chapter 6 - AI inference architecture questions — JR2018680 Interview Preparation.",
    "sections": [
      "➕ Additions",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 7 - HPC networking questions": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Chapter 7 - HPC networking questions — JR2018680 Interview Preparation.",
    "sections": [
      "Worked scenario",
      "➕ Additions",
      "size count type redop time algbw busbw",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 8 - Solutions architecture whiteboard method": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Chapter 8 - Solutions architecture whiteboard method — JR2018680 Interview Preparation.",
    "sections": [
      "Worked scenario",
      "➕ Additions",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 9 - Customer discovery interview": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Chapter 9 - Customer discovery interview — JR2018680 Interview Preparation.",
    "sections": [
      "➕ Additions"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 10 - Behavioral and stakeholder stories": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Chapter 10 - Behavioral and stakeholder stories — JR2018680 Interview Preparation.",
    "sections": [
      "➕ Additions",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 11 - Question bank: foundations to SA depth": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Chapter 11 - Question bank: foundations to SA depth — JR2018680 Interview Preparation.",
    "sections": [
      "➕ Additions",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Chapter 12 - 45-minute mock interview structure": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Chapter 12 - 45-minute mock interview structure — JR2018680 Interview Preparation.",
    "sections": [
      "Practice",
      "➕ Additions",
      "More practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Senior Interview Method — Clarify, model, hypothesize, test, recommend": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Senior Interview Method — Clarify, model, hypothesize, test, recommend — JR2018680 Interview Preparation.",
    "sections": [
      "➕ Additions"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Question set A — Linux and host mechanics": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Question set A — Linux and host mechanics — JR2018680 Interview Preparation.",
    "sections": [
      "➕ Additions",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Question set B — Python coding and production automation": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Question set B — Python coding and production automation — JR2018680 Interview Preparation.",
    "sections": [
      "Interview task skeleton: summarize failures by node and error type",
      "➕ Additions"
    ],
    "codeLanguages": [
      "python",
      "text"
    ]
  },
  "Question set C — Kubernetes platform depth": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Question set C — Kubernetes platform depth — JR2018680 Interview Preparation.",
    "sections": [
      "➕ Additions",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Question set D — GPU and accelerated networking": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Question set D — GPU and accelerated networking — JR2018680 Interview Preparation.",
    "sections": [
      "➕ Additions",
      "gpu sm mem enc dec mclk pclk",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Question set E — AI inference architecture": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Question set E — AI inference architecture — JR2018680 Interview Preparation.",
    "sections": [
      "➕ Additions"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Question set F — Customer architecture and PoC": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Question set F — Customer architecture and PoC — JR2018680 Interview Preparation.",
    "sections": [
      "➕ Additions",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Question set G — Whiteboard: production GenAI platform": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Question set G — Whiteboard: production GenAI platform — JR2018680 Interview Preparation.",
    "sections": [
      "➕ Additions"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Question set H — Behavioral stories for a senior SA": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Question set H — Behavioral stories for a senior SA — JR2018680 Interview Preparation.",
    "sections": [
      "➕ Additions",
      "Practice"
    ],
    "codeLanguages": [
      "text"
    ]
  },
  "Current role-family signals to be able to discuss": {
    "volume": "Volume 9",
    "lens": "senior interview reasoning across Python, Linux, Kubernetes, GPUs, AI inference, networking, architecture, discovery, and stakeholder scenarios",
    "learningOutcome": "Current role-family signals to be able to discuss — JR2018680 Interview Preparation.",
    "sections": [
      "➕ Additions"
    ],
    "codeLanguages": [
      "text"
    ]
  }
};
